Added binarysearch in python2
FOSS-UCSC/FOSSALGO pull request #391
Opened 2020-10-03 03:18 UTC by avsd47

**Hi!**  
Thanks for considering contributing to this ever-growing list of algorithm and data structure implementations.
Your contribution is valuable. Use the follow template for creating Pull Requests
---

**Fixes #377 **

By submitting this pull request I confirm I've read and complied with the below declarations.

- ✔   I have read the [Contribution guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md) 
and I am confident that my PR reflects them.

-  ✔ I have followed the [coding guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#cs) 
for this project.

- ✔ My code follows the [skeleton code structure](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#sample).

- ✔ This pull request has a descriptive title. 
For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.

- ✔ This pull request shall only be merged once the build passes.

- ✔ I have mentioned the issue number correctly (with hyper-link) in this pull request description.

2020-10-03 04:50 UTC, Danushka96 commented
Hi @avsd47 
I can't see any file changes here,

2020-10-03 08:28 UTC, RavinduSachintha requested changes
there is a little issue. just add a new line add the end of the file. It is about best practices, nothing else. :+1:

2020-10-03 08:59 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +    else:
Codacy found an issue: [Trailing whitespace](https://app.codacy.com/gh/FOSS-UCSC/FOSSALGO/pullRequest?prid=6277716)

2020-10-03 08:59 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +  while (low<=high):
Codacy found an issue: [Trailing whitespace](https://app.codacy.com/gh/FOSS-UCSC/FOSSALGO/pullRequest?prid=6277716)

2020-10-03 08:59 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +
Codacy found an issue: [Trailing whitespace](https://app.codacy.com/gh/FOSS-UCSC/FOSSALGO/pullRequest?prid=6277716)

2020-10-03 08:59 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +    print "The element is not found!"
Codacy found an issue: [invalid syntax (F999)](https://app.codacy.com/gh/FOSS-UCSC/FOSSALGO/pullRequest?prid=6277716)

2020-10-03 09:15 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +    else:
Codacy found an issue: [Trailing whitespace](https://app.codacy.com/gh/FOSS-UCSC/FOSSALGO/pullRequest?prid=6277716)

2020-10-03 09:15 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +  while(low<=high):
Codacy found an issue: [Trailing whitespace](https://app.codacy.com/gh/FOSS-UCSC/FOSSALGO/pullRequest?prid=6277716)

2020-10-03 09:15 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +
Codacy found an issue: [Trailing whitespace](https://app.codacy.com/gh/FOSS-UCSC/FOSSALGO/pullRequest?prid=6277716)

2020-10-03 09:15 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +    print "The element is not found!"
Codacy found an issue: [invalid syntax (F999)](https://app.codacy.com/gh/FOSS-UCSC/FOSSALGO/pullRequest?prid=6277716)

2020-10-03 13:30 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +  while(low<=high):
this is happening when you have added unwanted blank spaces at the end of the code lines. just remove them and the issue will be gone.

2020-10-03 13:31 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +    else:
this is also the same mistake.

2020-10-03 13:31 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +
same

2020-10-03 13:35 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +    print "The element is not found!"
you should use single quotations (not double quotations) with the print command. it is just a guidance rule.

2020-10-03 13:40 UTC, avsd47 commented
I edited it could you please review again and let me know if any issue persists

2020-10-03 13:53 UTC, RavinduSachintha commented
> I edited it could you please review again and let me know if any issue persists

Your changes didn't push to the PR yet.

2020-10-03 14:21 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +    else:
Codacy found an issue: [Trailing whitespace](https://app.codacy.com/gh/FOSS-UCSC/FOSSALGO/pullRequest?prid=6277716)

2020-10-03 14:21 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +  while(low<=high):
Codacy found an issue: [Trailing whitespace](https://app.codacy.com/gh/FOSS-UCSC/FOSSALGO/pullRequest?prid=6277716)

2020-10-03 14:21 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +  return -1
Codacy found an issue: [Trailing whitespace](https://app.codacy.com/gh/FOSS-UCSC/FOSSALGO/pullRequest?prid=6277716)

2020-10-03 14:21 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +    print 'The element is not found!'
Codacy found an issue: [invalid syntax (F999)](https://app.codacy.com/gh/FOSS-UCSC/FOSSALGO/pullRequest?prid=6277716)

2020-10-03 14:22 UTC, avsd47 commented
Thank you for your patience i=now igot clear understanding with the way github is working thanks a lot for being patient and i think now it's fine

2020-10-03 14:25 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +  while(low<=high):
there is an unwanted white space at the end of line 5.

2020-10-03 14:27 UTC, RavinduSachintha commented
> Thank you for your patiencenow i got clear understanding with the way github is working thanks a lot for being patient and i think now it's fine

nothing to worry about that. but still, you see some minor issues. right? until you fix them we can not merge to the master branch.

2020-10-03 14:40 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +    else:
Codacy found an issue: [Trailing whitespace](https://app.codacy.com/gh/FOSS-UCSC/FOSSALGO/pullRequest?prid=6277716)

2020-10-03 14:40 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +  while(low<=high):
Codacy found an issue: [Trailing whitespace](https://app.codacy.com/gh/FOSS-UCSC/FOSSALGO/pullRequest?prid=6277716)

2020-10-03 14:40 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +    print 'The element is not found!'
Codacy found an issue: [invalid syntax (F999)](https://app.codacy.com/gh/FOSS-UCSC/FOSSALGO/pullRequest?prid=6277716)

2020-10-03 14:40 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +
Codacy found an issue: [Trailing whitespace](https://app.codacy.com/gh/FOSS-UCSC/FOSSALGO/pullRequest?prid=6277716)

2020-10-03 14:40 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +  return -1
Codacy found an issue: [Trailing whitespace](https://app.codacy.com/gh/FOSS-UCSC/FOSSALGO/pullRequest?prid=6277716)

2020-10-03 15:33 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +  while(low<=high):
Codacy found an issue: [Trailing whitespace](https://app.codacy.com/gh/FOSS-UCSC/FOSSALGO/pullRequest?prid=6277716)

2020-10-03 15:33 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +  return -1
Codacy found an issue: [Trailing whitespace](https://app.codacy.com/gh/FOSS-UCSC/FOSSALGO/pullRequest?prid=6277716)

2020-10-03 15:33 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +    else:
Codacy found an issue: [Trailing whitespace](https://app.codacy.com/gh/FOSS-UCSC/FOSSALGO/pullRequest?prid=6277716)

2020-10-03 15:33 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +
Codacy found an issue: [Trailing whitespace](https://app.codacy.com/gh/FOSS-UCSC/FOSSALGO/pullRequest?prid=6277716)

2020-10-03 15:33 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +    print 'The element is not found!'
Codacy found an issue: [invalid syntax (F999)](https://app.codacy.com/gh/FOSS-UCSC/FOSSALGO/pullRequest?prid=6277716)

2020-10-05 03:29 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +  return -1
Codacy found an issue: [Trailing whitespace](https://app.codacy.com/gh/FOSS-UCSC/FOSSALGO/pullRequest?prid=6277716)

2020-10-05 03:29 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +    else:
Codacy found an issue: [Trailing whitespace](https://app.codacy.com/gh/FOSS-UCSC/FOSSALGO/pullRequest?prid=6277716)

2020-10-05 03:29 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +  while(low<=high):
Codacy found an issue: [Trailing whitespace](https://app.codacy.com/gh/FOSS-UCSC/FOSSALGO/pullRequest?prid=6277716)

2020-10-05 03:29 UTC, RavinduSachintha commented on algorithms/ar-bsrh/python2/binary_search.py
> +
Codacy found an issue: [Trailing whitespace](https://app.codacy.com/gh/FOSS-UCSC/FOSSALGO/pullRequest?prid=6277716)

2020-10-05 03:35 UTC, RavinduSachintha commented
@avsd47 If you wish to continue this contribution, you have to fix just a few minor issues here. Otherwise, we will have to close this PR without merging.

2020-10-05 04:30 UTC, avsd47 commented
I was a bit busy yesterday now i am looking into it,i will fix this soon

2020-10-05 04:41 UTC, avsd47 commented
Could you please review again i made some changes

2020-10-05 05:23 UTC, RavinduSachintha approved these changes
Nice work @avsd47 
It would be great if you can add this contribution to main README file too. You just need to copy-paste the phrase for "correct sign" to the right place in the algorithm chart. No need to make another PR. just change the README file and push it.

2020-10-05 05:46 UTC, avsd47 commented
Could you please review the changes i have added myself as contributor and also added the checkmark

2020-10-05 05:56 UTC, RavinduSachintha commented on README.md
> +    <td align="center"><a href="https://github.com/avsd47"><img src="https://avatars0.githubusercontent.com/u/47289942?s=400&u=29eb591b7decff18890e929d4c0593dd86f7236a&v=4" width="100px;" alt=""/><br
please revert this change. This part is handling by an automated robot.

2020-10-05 05:57 UTC, RavinduSachintha commented on README.md
> +| Binary Search                    | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |        | :white_check_mark: |       |            |
:+1:

2020-10-05 06:04 UTC, avsd47 commented
I reverted it could you please review it again

2020-10-05 06:36 UTC, RavinduSachintha commented
@all-contributors please add @avsd47  for code and doc
@avsd47 Thank you for your contribution. 
Good luck! :+1: 
Make sure to star this repository. :wink:

2020-10-05 06:36 UTC, merged