Added Insertion Sort in C#
FOSS-UCSC/FOSSALGO pull request #642
Opened 2020-10-17 10:45 UTC by riturajjain2000

**Fixes #633**

By submitting this pull request I confirm I've read and complied with the below declarations.

-   [x] I have read the [Contribution guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md) 
and I am confident that my PR reflects them.

-   [x] I have followed the [coding guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#cs) 
for this project.

-   [x] My code follows the [skeleton code structure](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#sample).

-   [x] This pull request has a descriptive title. 
For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.

-   [x] This pull request shall only be merged once the build passes.

-   [x] I have mentioned the issue number correctly (with hyper-link) in this pull request description.

2020-10-17 11:36 UTC, RavinduSachintha requested changes

2020-10-17 11:36 UTC, RavinduSachintha commented on README.md
> +<<<<<<< HEAD
please check the changes again. these parts are some remaining texts from conflicts. you have to remove them.

2020-10-18 04:57 UTC, RavinduSachintha approved these changes

2020-10-18 04:58 UTC, RavinduSachintha commented
@riturajjain2000 would you be able to add this contribution to the algorithm chart in the main readme file? don't change anything else. :+1:

2020-10-18 10:06 UTC, riturajjain2000 commented
> @riturajjain2000 would you be able to add this contribution to the algorithm chart in the main readme file? don't change anything else. 👍

Done

2020-10-18 11:35 UTC, RavinduSachintha approved these changes

2020-10-18 11:36 UTC, merged

2020-10-18 11:37 UTC, RavinduSachintha commented
@riturajjain2000 thank you for your contribution. Keep it up :+1:

2020-10-19 12:33 UTC, riturajjain2000 commented
Happy to help 😄