LCS using C
FOSS-UCSC/FOSSALGO pull request #832
Opened 2020-10-31 05:42 UTC by ashutosh007865

adding code for the longest common sequence using c

**Hi!**  
Thanks for considering for contributing to this ever-growing list of algorithm and data structure implementations.
Your contribution is valuable. Use the follow template for creating PRs. (Delete this part)
---

**Fixes #814 

By submitting this pull request I confirm I've read and complied with the below declarations.

-   [x] I have read the [Contribution guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md) 
and I am confident that my PR reflects them.

-   [x] I have followed the [coding guidelines](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#cs) 
for this project.

-   [ ] My code follows the [skeleton code structure](https://github.com/FOSS-UCSC/FOSSALGO/blob/master/CONTRIBUTING.md#sample).

-   [x] This pull request has a descriptive title. 
For example, `Added {Algorithm/DS name} [{Language}]`, not `Update README.md` or `Added new code`.

-   [x] This pull request shall only be merged once the build passes.

-   [ ] I have mentioned the issue number correctly (with hyper-link) in this pull request description.

2020-10-31 05:44 UTC, ashutosh007865 commented
please accept my PR

2020-10-31 13:36 UTC, Danushka96 requested changes

2020-10-31 13:36 UTC, Danushka96 commented on algorithms/ar-lcs/c/lcs.c
> +#include<bits/stdc++.h>
the compiler can't find this header, please use only inbuild libraries,

2020-11-06 13:36 UTC, Danushka96 commented
Closed due to inactivity

2020-11-06 13:36 UTC, closed without merging